apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: gitops-vm
spec:
  generators: []
  template:
    metadata:
      name: "gitops-vm"
    spec:
      project: default
      source:
        repoURL: https://github.com/arencloud/gitops-vm.git
        targetRevision: HEAD
        path: "kustomize/"
        kustomize:
          commonAnnotations:
            managed-cluster: "localcluster"
      destination:
        namespace: openshift-cnv
      syncPolicy:
        automated:
          selfHeal: true
          prune: true
