apiVersion: kubevirt.io/v1
kind: VirtualMachine
metadata:
  name: gitops-vm
spec:
  running: false
  dataVolumeTemplates:
    - metadata:
        name: gitops-vm-ds-fedora
      spec:
        sourceRef:
          kind: DataSource
          name: fedora
          namespace: openshift-virtualization-os-images
        storage:
          resources: {}
  template:
    spec:
      terminationGracePeriodSeconds: 180
      domain:
        devices:
          rng: {}
        memory:
          guest: 1024M
      volumes:
        - dataVolume:
            name: gitops-vm-ds-fedora
          name: gitops-vm-ds-fedora
        - cloudInitNoCloud:
            userData: |-
              #cloud-config
              user: fedora
              password: fedora
              chpasswd: { expire: False }
          name: cloudinitdisk