apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../base

patches:
  - patch: |
     - op: replace
       path: /spec/template/spec/domain/resources/requests/memory
       value: 2Gi
    target:
      kind: VirtualMachine